### ISSUE TITLE
Instructions to build from source?

### ISSUE THREAD

**Issue by acmcelwee** [tomvachon/dpaf#2]
@tomvachon this looks awesome. Any way you could add your build instructions to the README? I'd love to migrate to this from sudolikeaboss, but it would be rad if I could build it myself from source, considering the highly sensitive nature of the tool. I saw you mentioned sending the instructions to someone in [this comment](https://github.com/tomvachon/dpaf/issues/1#issuecomment-338954935), so I figured you probably had them handy and could add to the docs.

**Comment by tomvachon** [comment]
Sure, I have to pull it together, its in some scratch notes.

**Comment by tomvachon** [comment]
This has been published.  If you have issues, let me know
